import React, { forwardRef } from 'react';

const PrintView = forwardRef(({ recipe }, ref) => {
    if (!recipe) return null;

    return (
        <div ref={ref} style={{
            position: 'absolute',
            left: '-9999px',
            top: 0,
            width: '210mm',
            minHeight: '297mm',
            padding: '20mm',
            backgroundColor: 'white',
            color: 'black',
            zIndex: -1
        }}>
            <h1 style={{ textAlign: 'center' }}>{recipe.title}</h1>
            <hr />

            <h2>Ingredients</h2>
            <ul>
                {recipe.ingredients?.map((item, idx) => (
                    <li key={idx}>{item}</li>
                ))}
            </ul>

            <h2>Instructions</h2>
            <ol>
                {recipe.instructions?.map((step, idx) => (
                    <li key={idx}>{step}</li>
                ))}
            </ol>

            {recipe.macros && (
                <div className="macros">
                    <h3>Macros per serving</h3>
                    <ul>
                        {Object.entries(recipe.macros).map(([key, val]) => (
                            <li key={key}><strong>{key}:</strong> {val}</li>
                        ))}
                    </ul>
                </div>
            )}

            <div style={{ marginTop: '2rem', fontSize: '0.8rem', textAlign: 'center', color: '#666' }}>
                Generated by Switch-On Recipe Maker
            </div>
        </div>
    );
});

export default PrintView;
